In [1]:
import numpy as np

In [2]:
km = np.loadtxt('data/alura06/carros-km.txt')
anos = np.loadtxt('data/alura06/carros-anos.txt', dtype=int)

km_media = km / (2020-anos)

type(km_media)

numpy.ndarray

In [3]:
5//2

2

In [4]:
_ + _

4

In [5]:
for i in range(10):
    _+=_

_

4096

In [6]:
ano_atual = 2020
ano_fabricacao = 2003
km_total = 44410.0

km_media = km_total/(ano_atual-ano_fabricacao)

km_total += km_media

km_total

47022.35294117647

In [7]:
nome = "LeoLira"
print(f"Olá, {nome}")

Olá, LeoLira


In [8]:
l = ['0','0','1','1']

set(l)

{'0', '1'}

In [9]:
l1 = [0,1,2,3,4,5,6,7,8,9]

[i for i in l1 if i % 2 == 0]

[0, 2, 4, 6, 8]

In [10]:
import numpy as np

In [11]:
# np.arange(10)

np.array(['Leo'])

array(['Leo'], dtype='<U3')

In [12]:
np_array = np.arange(1000000)

In [13]:
py_list = list(range(1000000))

In [14]:
%time for _ in range(100) : np_array *= 2

CPU times: user 130 ms, sys: 3.38 ms, total: 133 ms
Wall time: 132 ms


In [15]:
%time for _ in range(100) : py_list = [x * 2 for x in py_list]

CPU times: user 6.09 s, sys: 1.15 s, total: 7.25 s
Wall time: 7.25 s


In [16]:
np.array([0,''])

array(['0', ''], dtype='<U21')

In [17]:
contador = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])

In [18]:
contador.reshape((6,2), order='C')

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
contador.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [20]:
km = np.loadtxt('data/alura06/carros-km.txt')
valor = np.loadtxt('data/alura06/carros-valor.txt')
anos = np.loadtxt('data/alura06/carros-anos.txt', dtype=int)

In [21]:
dataset = np.column_stack((anos,km,valor))

In [22]:
dataset.shape

(258, 3)

In [23]:
np.std(dataset, axis=0)

array([9.70703915e+00, 3.98598270e+04, 2.97541012e+04])

In [24]:
t = (0,1,2,3)
n1,n2,n3,n4 = t

In [25]:
l = [0,1,2]
sum(l)

3

In [26]:
def media(*n):
    return sum(list(n))/3


In [27]:
media(1,2,3)

2.0

In [28]:
import pandas as pd

In [29]:
carros=['Fusca', 'Passat', 'DS5']
carros

['Fusca', 'Passat', 'DS5']

In [30]:
pd.Series(carros)

0     Fusca
1    Passat
2       DS5
dtype: object

In [31]:
dados=[
    {"Nome":"Variant", "Motor":"Motor 4.0 Turbo", "Ano":2009, "KM":1452.0},
    {"Nome":"Passat", "Motor":"Motor Veio", "Ano":2000, "KM":5452.0},
    {"Nome":"Carrão", "Motor":"Motor Fudidão", "Ano":2020, "KM":252.0}
]

In [32]:
dataset = pd.DataFrame(dados)
dataset

Ano      KM            Motor     Nome
0  2009  1452.0  Motor 4.0 Turbo  Variant
1  2000  5452.0       Motor Veio   Passat
2  2020   252.0    Motor Fudidão   Carrão

In [33]:
dataset[["Nome","Ano","KM","Motor"]]

Nome   Ano      KM            Motor
0  Variant  2009  1452.0  Motor 4.0 Turbo
1   Passat  2000  5452.0       Motor Veio
2   Carrão  2020   252.0    Motor Fudidão

In [34]:
poke = pd.read_csv("data/pokemon_data.csv", index_col="Name")

In [35]:
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
poke.loc[:, ["Attack"]]
# sns.scatterplot(x="Sp. Atk", y="Speed", data=poke)

Attack
Name                             
Bulbasaur                      49
Ivysaur                        62
Venusaur                       82
VenusaurMega Venusaur         100
Charmander                     52
Charmeleon                     64
Charizard                      84
CharizardMega Charizard X     130
CharizardMega Charizard Y     104
Squirtle                       48
Wartortle                      63
Blastoise                      83
BlastoiseMega Blastoise       103
Caterpie                       30
Metapod                        20
Butterfree                     45
Weedle                         35
Kakuna                         25
Beedrill                       90
BeedrillMega Beedrill         150
Pidgey                         45
Pidgeotto                      60
Pidgeot                        80
PidgeotMega Pidgeot            80
Rattata                        56
Raticate                       81
Spearow                        60
Fearow                         90
Ekans                          60
Arbok                          85
...                           ...
Sylveon                        65
Hawlucha                       92
Dedenne                        58
Carbink                        50
Goomy                          50
Sliggoo                        75
Goodra                        100
Klefki                         80
Phantump                       70
Trevenant                     110
PumpkabooAverage Size          66
PumpkabooSmall Size            66
PumpkabooLarge Size            66
PumpkabooSuper Size            66
GourgeistAverage Size          90
GourgeistSmall Size            85
GourgeistLarge Size            95
GourgeistSuper Size           100
Bergmite                       69
Avalugg                       117
Noibat                         30
Noivern                        70
Xerneas                       131
Yveltal                       131
Zygarde50% Forme              100
Diancie                       100
DiancieMega Diancie           160
HoopaHoopa Confined           110
HoopaHoopa Unbound            160
Volcanion                     110

[800 rows x 1 columns]

In [37]:
poke.iloc[0:4, [0,2,4]]


#  Type 2  Attack
Name                                    
Bulbasaur              1  Poison      49
Ivysaur                2  Poison      62
Venusaur               3  Poison      82
VenusaurMega Venusaur  3  Poison     100

In [38]:
select1 = poke.Legendary == True
select2 = poke["Type 1"] == "Ice"

In [39]:
poke[(select) & (select2)]


NameError: name 'select' is not defined

In [ ]:
poke.query("Defense > 100 and Attack > 100")

In [ ]:
poke.info()

In [ ]:
poke[poke["Type 2"].isna()]

In [40]:
poke["Type 1"].str.get_dummies()
sns.scatterplot(x="Sp. Def", y="Speed", hue="Legendary", data=poke)

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  \
Name                                                                            
Bulbasaur                    0     0       0         0      0         0     0   
Ivysaur                      0     0       0         0      0         0     0   
Venusaur                     0     0       0         0      0         0     0   
VenusaurMega Venusaur        0     0       0         0      0         0     0   
Charmander                   0     0       0         0      0         0     1   
Charmeleon                   0     0       0         0      0         0     1   
Charizard                    0     0       0         0      0         0     1   
CharizardMega Charizard X    0     0       0         0      0         0     1   
CharizardMega Charizard Y    0     0       0         0      0         0     1   
Squirtle                     0     0       0         0      0         0     0   
Wartortle                    0     0       0         0      0         0     0   
Blastoise                    0     0       0         0      0         0     0   
BlastoiseMega Blastoise      0     0       0         0      0         0     0   
Caterpie                     1     0       0         0      0         0     0   
Metapod                      1     0       0         0      0         0     0   
Butterfree                   1     0       0         0      0         0     0   
Weedle                       1     0       0         0      0         0     0   
Kakuna                       1     0       0         0      0         0     0   
Beedrill                     1     0       0         0      0         0     0   
BeedrillMega Beedrill        1     0       0         0      0         0     0   
Pidgey                       0     0       0         0      0         0     0   
Pidgeotto                    0     0       0         0      0         0     0   
Pidgeot                      0     0       0         0      0         0     0   
PidgeotMega Pidgeot          0     0       0         0      0         0     0   
Rattata                      0     0       0         0      0         0     0   
Raticate                     0     0       0         0      0         0     0   
Spearow                      0     0       0         0      0         0     0   
Fearow                       0     0       0         0      0         0     0   
Ekans                        0     0       0         0      0         0     0   
Arbok                        0     0       0         0      0         0     0   
...                        ...   ...     ...       ...    ...       ...   ...   
Sylveon                      0     0       0         0      1         0     0   
Hawlucha                     0     0       0         0      0         1     0   
Dedenne                      0     0       0         1      0         0     0   
Carbink                      0     0       0         0      0         0     0   
Goomy                        0     0       1         0      0         0     0   
Sliggoo                      0     0       1         0      0         0     0   
Goodra                       0     0       1         0      0         0     0   
Klefki                       0     0       0         0      0         0     0   
Phantump                     0     0       0         0      0         0     0   
Trevenant                    0     0       0         0      0         0     0   
PumpkabooAverage Size        0     0       0         0      0         0     0   
PumpkabooSmall Size          0     0       0         0      0         0     0   
PumpkabooLarge Size          0     0       0         0      0         0     0   
PumpkabooSuper Size          0     0       0         0      0         0     0   
GourgeistAverage Size        0     0       0         0      0         0     0   
GourgeistSmall Size          0     0       0         0      0         0     0   
GourgeistLarge Size          0     0       0         0    